---
- hosts: all
  sudo: true
  roles:
    - role: wordpress
      wordpress_db_hostname: hostname
      wordpress_db_name: wordpress
      wordpress_db_user: wpuser
      wordpress_db_password: password

