---

# nginx folders
- name: config - ensure folders exists
  file:
    state=directory
    path={{ item }}
    mode=0755
  with_items:
    - "{{ wordpress_nginx_global_dir }}"
    - "{{ wordpress_fastcgi_cache_path }}"

- name: config - copy global nginx config
  copy:
    src=global/
    dest={{ wordpress_nginx_global_dir }}

- name: config - global templates
  template:
    src=global/{{ item }}.j2
    dest={{ wordpress_nginx_global_dir }}/{{ item }}
  with_items:
    - wordpress-pagespeed.conf

# nginx shared
- name: config - info dir
  file:
    state=directory
    path={{ wordpress_info_dir }}

- name: config - copy info
  copy:
    src=info.php
    dest={{ wordpress_info_dir }}/

- name: config - nginx shared config
  template:
    src=conf.d/{{ item }}.j2
    dest={{ wordpress_nginx_shared_dir }}/{{ item }}
    mode=0644
  with_items:
    - upstream-php.conf
    - phpinfo.conf
    - wordpress-includes.conf

# nginx wordpress site
- name: config - nginx wordpress site config
  template:
    src=wordpress.j2
    dest={{ wordpress_nginx_available_dir }}/{{ wordpress_root_domain }}
    mode=0644

- name: config - nginx wordpress site config
  template:
    src=wordpress.proxy_cache.j2
    dest={{ wordpress_nginx_available_dir }}/{{ wordpress_root_domain }}_proxy
    mode=0644

- name: config - nginx enable wordpress site
  file:
    state=link
    src={{ wordpress_nginx_available_dir }}/{{ wordpress_root_domain }}
    dest={{ wordpress_nginx_enabled_dir }}/{{ wordpress_root_domain }}

