---

# nginx global
- name: config - ensure global nginx folder exists
  file:
    state=directory
    path={{ wordpress_nginx_global_dir }}

- name: config - copy global nginx files
  copy:
    src=global/
    dest={{ wordpress_nginx_global_dir }}

# nginx shared
- name: config - info dir
  file:
    state=directory
    path={{ wordpress_info_dir }}

- name: config - copy info
  copy:
    src=info.php
    dest={{ wordpress_info_dir }}/

- name: config - nginx shared config
  template:
    src=conf.d/{{ item }}.j2
    dest={{ wordpress_nginx_shared_dir }}/{{ item }}
  with_items:
    - upstream-php.conf
    - phpinfo.conf

# nginx wordpress site
- name: config - nginx wordpress site config
  template:
    src=wordpress.j2
    dest={{ wordpress_nginx_available_dir }}/{{ wordpress_root_domain }}

- name: config - nginx enable wordpress site
  file:
    state=link
    src={{ wordpress_nginx_available_dir }}/{{ wordpress_root_domain }}
    dest={{ wordpress_nginx_enabled_dir }}/{{ wordpress_root_domain }}

# may want to remove this
#- name: config - default site
#  template:
#    src=default-site.j2
#    dest={{ wordpress_nginx_shared_dir }}/default-site
#

