---

- name: hhvm - hhvm key
  apt_key:
    url=http://dl.hhvm.com/conf/hhvm.gpg.key
    state=present

- name: hhvm - hhvm repo
  apt_repository:
    repo='deb http://dl.hhvm.com/ubuntu trusty main'
    state=present

- name: hhvm - hhvm apt-get
  apt:
    name=hhvm
    state=present
    update_cache=yes
    cache_valid_time=3600

- name: hhvm - config
  template:
    src=hhvm/server.ini.j2
    dest=/etc/hhvm/server.ini
    mode=0644

 - name: hhvm - logging php.ini
  template:
    src=hhvm/php.ini
    dest=/etc/hhvm/php.ini
    mode=0644
