---

- name: dependencies
  include: depend.yml

- name: debian install
  include: install_debian.yml
  when: ansible_os_family == 'Debian'

- name: configure
  include: config.yml

- name: configure nginx
  include: config_nginx.yml

- name: service
  include: service.yml

