---
- name: php5-fpm - depend
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - php5-fpm
    - php5-mysql
    - php5-mcrypt
    - php5-gd
    - php5-curl

- name: php5-fpm - config
  template:
    src=php5/fpm/pool.d/www.conf
    dest=/etc/php5/fpm/pool.d/www.conf
    mode=0644
